In [1]:
import pandas as pd
import numpy as np

In [2]:
x1=np.random.randint(low=1,high=20,size=(50,))

In [3]:
x2=np.random.randint(low=1,high=20,size=50)

In [4]:
 y=3+2*x1-4*x2+np.random.random((50,))

In [5]:
x=pd.DataFrame({'intercept':np.ones_like(x1),'x1':x1,'x2':x2})



In [14]:
w=np.zeros(x.shape[1])
w

array([0., 0., 0.])

In [21]:
def mypredictions(features,weights):
    predictions=np.dot(features,weights) #dot gives dot product
    return(predictions)
mypredictions(x,w)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
def myerror(target,features,weights):
    error=target-mypredictions(features,weights)
    return(error)

In [26]:
def mycost(target,features,weights):
    error=myerror(target,features,weights)
    cost=np.dot(error.T,error)
    return(cost)

In [27]:
mycost(y,x,w)

31415.19794065957

In [28]:
def gradient(target,features,weights):
    error=myerror(target,features,weights)
    gradient=-np.dot(features.T,error)
    return(gradient)

In [29]:
gradient(y,x,w)

array([  671.2414452 ,  6209.96448997, 11544.58398772])

In [ ]:
def my_lr(target,features,learning_rate):
    weights=np.zeros(features.shape[1])
    for i in np.arange(1000000):
        weights=weights-learning_rate*gradient(target,features,weights)
        weights[0]-=10*learning_rate*gradient(target,features,weights)[0]
        if i%10000==0:
            print(mycost(target,features,weights),weights)
    return(weights)
    
        
    

In [ ]:
my_lr(y,x,0.000001)

31063.60999745047 [-0.00729815 -0.00620996 -0.01154458]
21.678100358183915 [ 2.00049311  2.08272895 -3.95385787]
7.11255894886645 [ 2.85330572  2.03489862 -3.97982194]
4.256047837071174 [ 3.23094441  2.0136068  -3.99120222]
3.6958403731385365 [ 3.39818164  2.00417771 -3.99624196]
3.5859747397282273 [ 3.47224262  2.00000204 -3.99847381]
3.564428333830862 [ 3.50504051  1.99815284 -3.99946219]
3.560202739414423 [ 3.51956505  1.99733393 -3.99989989]
3.559374032842335 [ 3.52599724  1.99697127 -4.00009373]
3.559211510244343 [ 3.52884574  1.99681067 -4.00017957]
3.5591796369664523 [ 3.53010719  1.99673954 -4.00021758]
3.559173386107468 [ 3.53066583  1.99670805 -4.00023442]
3.5591721602141475 [ 3.53091322  1.9966941  -4.00024187]
3.5591719197968934 [ 3.53102278  1.99668792 -4.00024517]


In [35]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr=LinearRegression()

In [ ]:
lr.fit(x.iloc[:,1:],y)

In [ ]:
lr.coef_

In [ ]:
lr.intercept_